nodes:
- input.visual:
    source: 'demo/jumping_jacks.mp4'
- model.yolo:
    detect: ["person"]
- dabble.bbox_to_btm_midpoint
- dabble.zone_count:
    resolution: [960, 540]
    zones: [
      [[0, 0], [0.6, 0], [0.6, 1], [0, 1]], 
      [[0.6, 0], [1, 0], [1, 1], [0.6, 1]]
    ]

- dabble.tracking
- custom_nodes.dabble.timer
- custom_nodes.dabble.jump:
    threshold: 5
- dabble.statistics:
    maximum: obj_attrs["ids"]
- custom_nodes.dabble.count_in_zone
- dabble.fps
- draw.bbox
- draw.zones
- draw.tag:
    show: ["times", "jumps", "zones"] # can get direction if you want
- draw.legend:
    show: ["fps", "zone_count_people", "zone_count_jump"]
- output.media_writer:
    output_dir: "output"